name: Java Tests CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: sql123
          MYSQL_DATABASE: ecommjava
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    # Set up MySQL client
    - name: Set up MySQL client
      run: sudo apt-get install -y mysql-client

    # Run the MySQL script
    - name: Run MySQL script
      run: |
        sleep 10;
        mysql -h 127.0.0.1 -u root -psql123 ecommjava < JtProject/basedata.sql

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Test with Maven
      run: cd JtProject; mvn test
